### ISSUE TITLE
Suggestion for 01-tripleo-cheatsheet-deploying-tripleo.odt

### ISSUE THREAD

**Issue by fultonj** [ccamacho/tripleo-graphics#1]
You might want to change: 
"The goal of this upstream cheatsheet is to show how can be deployed a virtual"

To:
"The goal of this upstream cheatsheet is to show how to deploy a virtual"

Looks great otherwise. Thanks!

**Comment by ccamacho** [comment]
Done!
Thanks a lot for the review.
